/*
 * This source file was generated by the Gradle 'init' task
 */
package ifsc.poo;

public class App {

    public static void main(String[] args) {

        Lampada a = new Lampada(true);
        Lampada b = new Lampada(true);
        a.ligar();
        System.out.println(a.verEstado());
        a.desligar();
        System.out.println(b.verEstado());

    }

}
